version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    env_file: 
      - ./.env
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/package.json:/usr/src/app/package.json
    networks:
      - app-network
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file: 
      - ./.env
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/package.json:/usr/src/app/package.json
      - ./server/nodemon.json:/usr/src/app/nodemon.json
      - ./server/public:/usr/src/app/public
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/usr/src/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/samantacalling.uxlivinglab.online/fullchain.pem:/etc/letsencrypt/live/samantacalling.uxlivinglab.online/fullchain.pem:ro
      - /etc/letsencrypt/live/samantacalling.uxlivinglab.online/privkey.pem:/etc/letsencrypt/live/samantacalling.uxlivinglab.online/privkey.pem:ro
    restart: always
    networks:
      - app-network
    depends_on:
      - client
      - server

networks:
  app-network:
    driver: bridge